#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if is-bool-val-true "${CONTAINER_DEBUG:-0}"; then
    echo "1"
else
    # Do not set the variable.
    exit 100
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
