#
# nginx-proxy-manager Dockerfile
#
# https://github.com/jlesage/docker-nginx-proxy-manager
#

# Pull base image.
FROM jlesage/nginx-proxy-manager:latest

# Install Nginx Proxy Manager.
RUN \
    # Change the HTTP port 8080 to the unprivileged port 54380.
    sed-patch 's|8080;|54380;|' /etc/nginx/conf.d/default.conf && \
    sed-patch 's|"8080";|"54380";|' /etc/nginx/conf.d/default.conf && \
    sed-patch 's|listen 8080;|listen 54380;|' /opt/nginx-proxy-manager/templates/letsencrypt-request.conf && \
    sed-patch 's|:8080;|:54380;|' /opt/nginx-proxy-manager/templates/letsencrypt-request.conf && \
    sed-patch 's|listen 8080;|listen 54380;|' /opt/nginx-proxy-manager/templates/_listen.conf && \
    sed-patch 's|:8080;|:54380;|' /opt/nginx-proxy-manager/templates/_listen.conf && \
    sed-patch 's|listen 8080 |listen 54380 |' /opt/nginx-proxy-manager/templates/default.conf && \
    sed-patch 's|:8080;|:54380;|' /opt/nginx-proxy-manager/templates/default.conf && \

    # Change the HTTPs port 4443 to the unprivileged port 54343.
    sed-patch 's|4443 |54343 |' /etc/nginx/conf.d/default.conf && \
    sed-patch 's|"4443";|"54343";|' /etc/nginx/conf.d/default.conf && \
    sed-patch 's|listen 4443 |listen 54343 |' /opt/nginx-proxy-manager/templates/_listen.conf && \
    sed-patch 's|:4443;|:54343;|' /opt/nginx-proxy-manager/templates/_listen.conf

# Expose ports.
#   - 54380: HTTP traffic
#   - 54343: HTTPs traffic
#   - 8181: Management web interface
EXPOSE 54380 54343 8181
