#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

mkdir -p /run/mysqld
chown $USER_ID:$GROUP_ID /run/mysqld

MYSQLD_CMD="/usr/bin/mysqld --datadir /config/mysql --tmpdir /tmp/"

echo "[$(basename "$(pwd)")] starting..."
if [ -d  /var/run/s6/services/mysqld ]; then
    # Supervisor is running.
    exec /bin/s6-notifyoncheck s6-applyuidgid -u $USER_ID -g $GROUP_ID -G ${SUP_GROUP_IDS:-$GROUP_ID} $MYSQLD_CMD
else
    # Supervisor is not running: we are starting the db from the init script.
    exec s6-applyuidgid -u $USER_ID -g $GROUP_ID -G ${SUP_GROUP_IDS:-$GROUP_ID} $MYSQLD_CMD
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
