#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo 'SELECT 1' | mysql &> /dev/null
#[ -f /config/mysql/.initialized ] && echo 'SELECT 1' | mysql &> /dev/null

# vim:ft=sh:ts=4:sw=4:et:sts=4
