#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.

# Run weekly.
INTERVAL_IN_SECS=604800

# Make sure we appear with a proper name under `ps`.
if [ ! -L "$0" ]; then
    SV_NAME="$(basename "$(pwd)")"
    ln -sf run "$SV_NAME"
    exec ./"$SV_NAME" "$@"
fi

log() {
    if [ -n "${1-}" ]; then
        echo "[$(basename "$0")] $*"
    else
        while read OUTPUT; do
            echo "[$(basename "$0")] $OUTPUT"
        done
    fi
}

log "starting..."
s6-applyuidgid -u $USER_ID -g $GROUP_ID -G ${SUP_GROUP_IDS:-$GROUP_ID} /usr/local/bin/watch -i "$INTERVAL_IN_SECS" /opt/nginx-proxy-manager/bin/lecleaner | log

# vim:ft=sh:ts=4:sw=4:et:sts=4
