name: Docker Image CI/ CD
env:
  DOCKER_REG: xxx
  REG: xxx
  IMAGE_NAME: nginx-proxy-manager
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker
      run: 
        echo "${{ secrets.PASSWORD }}" | docker login $REG -u "${{ secrets.USERNAME }}" --password-stdin
    - name: Build image
      run:
        docker build . --file Dockerfile --tag $IMAGE_NAME
    - name: Push Image
      run: |
        # 拼接镜像 id，这个镜像 id 就是在使用 docker 镜像时 pull 后面的名字。
        IMAGE_ID=libra146/$IMAGE_NAME

        # 将所有的大写字母转为小写
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # 从 GitHub.ref 中取出版本
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
        # 从 tag 名字中替换 v 字符
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$DOCKER_REG
        echo VERSION=$VERSION
        
        # 设置镜像 id 和版本号
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        # 进行 push
        docker push $IMAGE_ID:$VERSION